'use client';

import React, { useEffect, useState } from 'react';
import { useApp } from '@/components/AppContext';
import PostCard from '@/components/PostCard';
import { ShieldCheck, Flame, AlertCircle, TrendingUp, Award, DollarSign } from 'lucide-react';
import Link from 'next/link';
import { t } from '@/lib/translations';

export default function HomePage() {
  const { language, loading: contextLoading } = useApp();
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState(null);
  const [page, setPage] = useState(1);
  const [totalPosts, setTotalPosts] = useState(0);

  useEffect(() => {
    if (contextLoading) return;
    setPosts([]);
    setTotalPosts(0);
    setPage(1);
  }, [language, contextLoading]);

  useEffect(() => {
    if (contextLoading) return;

    const fetchPosts = async (currentPage) => {
      if (currentPage === 1) {
        setLoading(true);
      } else {
        setLoadingMore(true);
      }
      setError(null);

      try {
        const generalRes = await fetch(`/api/posts?lang=${language}&limit=15&page=${currentPage}&_t=${Date.now()}`);
        const generalData = await generalRes.json();

        if (generalData.success) {
          setTotalPosts(generalData.total || 0);
          setPosts((prevPosts) =>
            currentPage === 1 ? generalData.posts : [...prevPosts, ...generalData.posts]
          );
        } else {
          throw new Error(generalData.error);
        }
      } catch (err) {
        console.error('Failed to load homepage posts:', err);
        setError('Could not connect to the news feed. Please try again.');
      } finally {
        setLoading(false);
        setLoadingMore(false);
      }
    };

    fetchPosts(page);
  }, [language, contextLoading, page]);

  const featuredPost = posts[0];
  const remainingPosts = posts.slice(1);

  if (contextLoading) {
    return <HomeSkeleton />;
  }

  return (
    <div className="w-full px-4 py-8 sm:px-6 lg:px-8 space-y-10">
      
      {/* Editorial Pledge & Fact Verification Bar - Newspaper Style */}
      <div className="rounded-3xl border border-zinc-300 bg-white p-5 sm:p-6 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 left-0 h-full w-[4px] bg-zinc-800"></div>
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5 justify-between relative z-10">
          <div className="flex items-start gap-4">
            <div className="rounded-2xl bg-zinc-100 p-3 border border-zinc-200 text-zinc-800">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <div>
              <h4 className="text-sm font-bold text-zinc-950 uppercase tracking-wider">{t('trustIndex', language)}</h4>
              <p className="text-sm text-zinc-700 leading-7 mt-2 max-w-2xl font-semibold">
                Every news item displays 100-150 word factual summaries generated by AI. We attribute original publishers, link back to full sources, and never copy full sentences or rewrite stories line-by-line.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 self-stretch sm:self-auto justify-end border-t border-zinc-100 sm:border-0 pt-4 sm:pt-0 shrink-0">
            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Active Standard</span>
            <span className="rounded-full bg-emerald-50 border border-emerald-250 px-3 py-1 text-[10px] font-extrabold text-emerald-800">VERIFIED FAIR USE</span>
          </div>
        </div>
      </div>

      {/* Main Grid Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* LEFT COLUMN: News Content Feed */}
        <div className="lg:col-span-8 space-y-10">
          
          {/* Main Trending Stories Feed */}
          <section className="space-y-6">
            <div className="flex items-center justify-between border-b border-zinc-300 pb-3">
              <h2 className="text-base font-black text-zinc-950 flex items-center gap-2 uppercase tracking-wider font-serif">
                <Flame className="h-5 w-5 text-brand-yellow" />
                {t('trendingStories', language)}
              </h2>
            </div>

            {loading ? (
              <div className="space-y-10">
                <div className="h-[320px] w-full rounded-3xl bg-zinc-200/50 animate-pulse"></div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                  {[...Array(8)].map((_, i) => <CardSkeleton key={i} />)}
                </div>
              </div>
            ) : error ? (
              <div className="rounded-3xl border border-zinc-300 p-8 text-center max-w-sm mx-auto space-y-4">
                <AlertCircle className="h-10 w-10 text-rose-600 mx-auto" />
                <p className="text-sm text-zinc-700 font-bold uppercase tracking-wider">{error}</p>
              </div>
            ) : posts.length === 0 ? (
              <div className="rounded-3xl border border-zinc-300 bg-white p-12 text-center text-zinc-500 font-semibold italic shadow-sm">
                {t('noPosts', language)}
              </div>
            ) : (
              <div className="space-y-8">
                
                {/* Featured Headline spotlight */}
                {featuredPost && (
                  <div className="group relative overflow-hidden rounded-3xl border border-zinc-300 bg-white transition-all duration-300 hover:border-zinc-400 shadow-md">
                    <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
                      <div className="md:col-span-7 relative aspect-video w-full overflow-hidden bg-zinc-100">
                        <img
                          src={featuredPost.imageUrl || 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80'}
                          alt={featuredPost.title}
                          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.01]"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-zinc-950/20 to-transparent"></div>
                      </div>
                      <div className="md:col-span-5 p-6 md:p-8 flex flex-col justify-center">
                        <span className="self-start rounded bg-brand-yellow text-brand-dark px-2.5 py-0.5 text-[9px] font-extrabold uppercase tracking-wider mb-4 font-serif">
                          {t('featured', language)} • {featuredPost.category}
                        </span>
                        <h1 className="text-lg sm:text-xl lg:text-2xl font-black text-zinc-950 leading-tight group-hover:text-brand-slate transition-colors font-serif">
                          <Link href={`/posts/${featuredPost.slug}`}>{featuredPost.title}</Link>
                        </h1>
                        <p className="mt-4 text-xs sm:text-sm leading-relaxed text-zinc-650 font-medium line-clamp-3">
                          {featuredPost.summary}
                        </p>
                        <div className="mt-6 flex items-center justify-between border-t border-zinc-200 pt-4">
                          <span className="text-xs text-zinc-500 font-semibold">{featuredPost.sourceName}</span>
                          <Link
                            href={`/posts/${featuredPost.slug}`}
                            className="rounded-xl bg-zinc-100 border border-zinc-300 hover:border-zinc-400 px-4 py-2 text-xs font-bold text-zinc-700 hover:text-zinc-900 transition-all cursor-pointer"
                          >
                            {t('readSummary', language)}
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Grid layout for standard cards */}
                {remainingPosts.length > 0 && (
                  <>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 pt-4 items-stretch">
                      {remainingPosts.map((post) => (
                        <PostCard key={post._id} post={post} layout="narrow" />
                      ))}
                    </div>
                    {totalPosts > posts.length && (
                      <div className="flex justify-center pt-8">
                        <button
                          onClick={() => setPage((prev) => prev + 1)}
                          disabled={loadingMore}
                          className="rounded-3xl bg-brand-slate px-6 py-3 text-xs font-black uppercase tracking-widest text-white transition hover:bg-brand-slate-dark disabled:cursor-not-allowed disabled:bg-zinc-400"
                        >
                          {loadingMore ? 'Loading more posts...' : 'Show more posts'}
                        </button>
                      </div>
                    )}
                  </>
                )}
              </div>
            )}
          </section>
        </div>

        {/* RIGHT COLUMN: Sidebar */}
        <div className="lg:col-span-4 space-y-8">

          {/* Quick Stats panel */}
          <div className="rounded-3xl border border-zinc-300 bg-white p-6 space-y-4 shadow-sm">
            <h3 className="text-sm font-black text-zinc-950 uppercase tracking-wider flex items-center gap-2">
              <Award className="h-4 w-4 text-amber-600" />
              {t('trustIndex', language)}
            </h3>
            <p className="text-xs text-zinc-650 leading-relaxed font-medium">
              Our automated models calculate fact credibility indexes before publishing. Any source post showing below 60% confidence is automatically quarantined for audit to ensure zero clickbait.
            </p>
            <div className="border-t border-zinc-200 pt-4 space-y-2">
              <div className="flex justify-between items-center text-xs">
                <span className="text-zinc-500 font-semibold">{t('verificationStandard', language)}:</span>
                <span className="font-extrabold text-emerald-600">HIGH</span>
              </div>
              <div className="flex justify-between items-center text-xs">
                <span className="text-zinc-500 font-semibold">{t('aggregationCycle', language)}:</span>
                <span className="font-extrabold text-zinc-850">Every 24 Hours</span>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}

// Loading Skeleton Components
function HomeSkeleton() {
  return (
    <div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-10 animate-pulse">
      <div className="h-20 w-full rounded-2xl bg-zinc-200"></div>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-8 space-y-8">
          <div className="h-6 w-32 bg-zinc-200 rounded"></div>
          <div className="flex flex-col gap-6">
            {[...Array(2)].map((_, i) => <CardSkeleton key={i} />)}
          </div>
        </div>
        <div className="lg:col-span-4 h-[300px] bg-zinc-200 rounded-3xl"></div>
      </div>
    </div>
  );
}

function CardSkeleton() {
  return (
    <div className="rounded-2xl border border-zinc-200 bg-white p-4 space-y-4">
      <div className="aspect-video w-full rounded-xl bg-zinc-150"></div>
      <div className="h-4 w-1/3 bg-zinc-150 rounded"></div>
      <div className="h-6 w-5/6 bg-zinc-150 rounded"></div>
    </div>
  );
}
